export const products = [
  {
    id: 1,
    name: 'Fender Stratocaster',
    price: 1299,
    quantity: 1,
    rating: 5,
    images: [
      '/placeholder.svg?height=500&width=500',
      '/placeholder.svg?height=500&width=500',
      '/placeholder.svg?height=500&width=500',
    ],
    badge: 'Best Seller',
    category: 'guitars',
    description:
      "The iconic Fender Stratocaster delivers the sound that's been heard on countless hit records. This versatile electric guitar features three single-coil pickups, a comfortable contoured body, and the classic Stratocaster tone that has defined rock, blues, and pop music for decades.",
    features: [
      'Alder body with gloss polyurethane finish',
      "Maple neck with modern 'C' shape",
      'Three single-coil Stratocaster pickups',
      '5-position pickup selector switch',
      'Synchronized tremolo bridge',
      '22 medium jumbo frets',
    ],
    specifications: {
      'Body Material': 'Alder',
      'Neck Material': 'Maple',
      Fingerboard: 'Maple',
      'Scale Length': '25.5 inches',
      'Number of Frets': '22',
      'Pickup Configuration': 'SSS',
      Bridge: 'Synchronized Tremolo',
      'Tuning Machines': 'Standard Die-Cast',
    },
    inStock: true,
    reviews: 127,
  },
  {
    id: 2,
    name: 'Yamaha Digital Piano',
    price: 899,
    quantity: 1,
    rating: 5,
    images: [
      '/placeholder.svg?height=500&width=500',
      '/placeholder.svg?height=500&width=500',
      '/placeholder.svg?height=500&width=500',
    ],
    badge: 'New',
    category: 'keyboards',
    description:
      'A versatile Yamaha digital piano offering authentic acoustic piano touch and tone in a compact and stylish design.',
    features: [
      '88 weighted keys with Graded Hammer Standard action',
      'Pure CF Sound Engine',
      'Built-in reverb and chorus effects',
      'USB to Host connectivity',
      'Dual and Split mode',
      'Compact and lightweight',
    ],
    specifications: {
      'Keyboard Type': 'Graded Hammer',
      Polyphony: '192 notes',
      'Number of Voices': '10',
      Amplifiers: '6W + 6W',
      Dimensions: '52.2" x 11.6" x 6.0"',
      Weight: '25 lbs',
      Connectivity: 'USB, AUX out',
    },
    inStock: true,
    reviews: 98,
  },
  {
    id: 3,
    name: 'Pearl Drum Kit',
    price: 2199,
    quantity: 1,
    rating: 4,
    images: [
      '/placeholder.svg?height=500&width=500',
      '/placeholder.svg?height=500&width=500',
      '/placeholder.svg?height=500&width=500',
    ],
    badge: 'Professional',
    category: 'drums',
    description:
      'Pearl’s professional drum kit for live performance and studio recording with high-quality shells and hardware.',
    features: [
      '6-ply maple shells',
      'Remo drum heads',
      'Chrome hardware',
      'Double-braced stands',
      'Adjustable tom mounts',
      'High-gloss lacquer finish',
    ],
    specifications: {
      'Shell Material': 'Maple',
      Configuration: '5-piece',
      Finish: 'Lacquer',
      Hoops: 'Triple-flanged',
      'Bearing Edge': '45 degrees',
      'Hardware Included': 'Yes',
    },
    inStock: true,
    reviews: 76,
  },
  {
    id: 4,
    name: 'Audio-Technica Headphones',
    price: 199,
    quantity: 1,
    rating: 5,
    images: [
      '/placeholder.svg?height=500&width=500',
      '/placeholder.svg?height=500&width=500',
      '/placeholder.svg?height=500&width=500',
    ],
    badge: 'Popular',
    category: 'audio',
    description:
      'Professional monitor headphones with excellent clarity, extended frequency response, and durable construction.',
    features: [
      '40mm drivers',
      'Extended frequency range',
      'Circumaural design',
      'Detachable cable',
      'Collapsible for portability',
      'Padded ear cups for comfort',
    ],
    specifications: {
      'Driver Diameter': '40 mm',
      'Frequency Response': '15–28,000 Hz',
      Sensitivity: '99 dB',
      Impedance: '38 ohms',
      Weight: '285 g',
      Cable: '3m straight / coiled',
    },
    inStock: true,
    reviews: 212,
  },
  {
    id: 5,
    name: 'Gibson Les Paul',
    price: 2499,
    quantity: 1,
    rating: 5,
    images: [
      '/placeholder.svg?height=500&width=500',
      '/placeholder.svg?height=500&width=500',
      '/placeholder.svg?height=500&width=500',
    ],
    badge: 'Premium',
    category: 'guitars',
    description:
      'The legendary Gibson Les Paul delivers unmatched sustain and tone, loved by guitarists worldwide.',
    features: [
      'Mahogany body with maple top',
      'Mahogany neck with rosewood fingerboard',
      'Burstbucker pickups',
      'Tune-o-matic bridge',
      'Nitrocellulose finish',
      'Cream binding',
    ],
    specifications: {
      'Body Material': 'Mahogany/Maple',
      'Neck Material': 'Mahogany',
      Fingerboard: 'Rosewood',
      'Scale Length': '24.75 inches',
      'Number of Frets': '22',
      'Pickup Configuration': 'HH',
      Bridge: 'Tune-o-matic',
      'Tuning Machines': 'Grover',
    },
    inStock: true,
    reviews: 184,
  },
  {
    id: 6,
    name: 'Roland Electronic Drums',
    price: 1799,
    quantity: 1,
    rating: 4,
    images: [
      '/placeholder.svg?height=500&width=500',
      '/placeholder.svg?height=500&width=500',
      '/placeholder.svg?height=500&width=500',
    ],
    badge: 'Electronic',
    category: 'drums',
    description:
      'High-performance Roland electronic drum kit with responsive pads and realistic sound.',
    features: [
      'Mesh-head pads',
      'Dynamic sound module',
      'USB/MIDI connectivity',
      'Compact and foldable',
      'Built-in coaching functions',
      'Quiet operation',
    ],
    specifications: {
      Pads: 'Mesh-head',
      Modules: 'TD-series',
      Kits: '50 preset',
      Songs: '50 demo',
      Connectivity: 'MIDI, USB',
      Weight: '45 lbs',
    },
    inStock: true,
    reviews: 89,
  },
  {
    id: 7,
    name: 'Shure SM58 Microphone',
    price: 99,
    quantity: 1,
    rating: 5,
    images: [
      '/placeholder.svg?height=500&width=500',
      '/placeholder.svg?height=500&width=500',
      '/placeholder.svg?height=500&width=500',
    ],
    badge: 'Classic',
    category: 'audio',
    description:
      'The industry-standard Shure SM58 dynamic vocal microphone known for reliability and quality.',
    features: [
      'Cardioid pickup pattern',
      'Frequency response tailored for vocals',
      'Pneumatic shock-mount system',
      'Durable construction',
      'Steel mesh grille',
      'Internal pop filter',
    ],
    specifications: {
      Type: 'Dynamic',
      'Polar Pattern': 'Cardioid',
      'Frequency Response': '50–15,000 Hz',
      Sensitivity: '-54.5 dBV/Pa',
      Connector: 'XLR',
      Weight: '298 g',
    },
    inStock: true,
    reviews: 430,
  },
  {
    id: 8,
    name: 'Korg Synthesizer',
    price: 1599,
    quantity: 1,
    rating: 4,
    images: [
      '/placeholder.svg?height=500&width=500',
      '/placeholder.svg?height=500&width=500',
      '/placeholder.svg?height=500&width=500',
    ],
    badge: 'Synth',
    category: 'keyboards',
    description:
      'Powerful Korg synthesizer packed with features and an intuitive interface for sound creation.',
    features: [
      '37 velocity-sensitive keys',
      'Multiple oscillators',
      'Extensive modulation capabilities',
      'Built-in effects',
      'Arpeggiator and sequencer',
      'Lightweight design',
    ],
    specifications: {
      Keys: '37',
      Polyphony: '16 voices',
      Oscillators: '3 per voice',
      Filter: 'Multi-mode',
      Connectivity: 'MIDI, USB',
      Weight: '8 lbs',
    },
    inStock: true,
    reviews: 73,
  },
  {
    id: 9,
    name: 'Taylor Acoustic Guitar',
    price: 1899,
    quantity: 1,
    rating: 5,
    images: [
      '/placeholder.svg?height=500&width=500',
      '/placeholder.svg?height=500&width=500',
      '/placeholder.svg?height=500&width=500',
    ],
    badge: 'Acoustic',
    category: 'guitars',
    description:
      'Premium Taylor acoustic guitar with brilliant tone and excellent playability.',
    features: [
      'Solid Sitka spruce top',
      'Indian rosewood back and sides',
      'Ebony fingerboard',
      'Gloss finish',
      'Taylor Expression System 2',
      'Deluxe hardshell case',
    ],
    specifications: {
      'Top Material': 'Sitka spruce',
      'Back & Sides': 'Rosewood',
      Neck: 'Tropical Mahogany',
      Fingerboard: 'Ebony',
      'Scale Length': '25.5 inches',
      Frets: '20',
      Pickup: 'ES2',
    },
    inStock: true,
    reviews: 142,
  },
  {
    id: 10,
    name: 'Casio Digital Piano',
    price: 599,
    quantity: 1,
    rating: 4,
    images: [
      '/placeholder.svg?height=500&width=500',
      '/placeholder.svg?height=500&width=500',
      '/placeholder.svg?height=500&width=500',
    ],
    badge: 'Budget',
    category: 'keyboards',
    description:
      'Affordable Casio digital piano perfect for beginners and intermediate players.',
    features: [
      '88 weighted keys',
      'Scaled Hammer Action',
      'Built-in speakers',
      'Various instrument tones',
      'Compact design',
      'Battery or AC power',
    ],
    specifications: {
      Keys: '88',
      Polyphony: '64 notes',
      Dimensions: '52" x 11" x 5"',
      Weight: '24 lbs',
      Power: 'Battery/AC',
      Connectivity: 'USB',
    },
    inStock: true,
    reviews: 65,
  },
  {
    id: 11,
    name: 'DW Drum Set',
    price: 3299,
    quantity: 1,
    rating: 5,
    images: [
      '/placeholder.svg?height=500&width=500',
      '/placeholder.svg?height=500&width=500',
      '/placeholder.svg?height=500&width=500',
    ],
    badge: 'Pro',
    category: 'drums',
    description:
      'Top-of-the-line DW drum set delivering superior tone, craftsmanship, and projection.',
    features: [
      'North American maple shells',
      'Custom hardware finishes',
      'Precision bearing edges',
      'STM tom mounts',
      'Reinforcement hoops',
      'Gloss lacquer finish',
    ],
    specifications: {
      'Shell Material': 'Maple',
      Configuration: '5-piece',
      Finish: 'Lacquer',
      'Bearing Edge': '45 degrees',
      Hoops: 'Die-cast',
      'Hardware Included': 'Yes',
    },
    inStock: true,
    reviews: 52,
  },
  {
    id: 12,
    name: 'Sony Studio Headphones',
    price: 299,
    quantity: 1,
    rating: 4,
    images: [
      '/placeholder.svg?height=500&width=500',
      '/placeholder.svg?height=500&width=500',
      '/placeholder.svg?height=500&width=500',
    ],
    badge: 'Studio',
    category: 'audio',
    description:
      'Sony professional studio headphones with accurate sound reproduction and high comfort for long sessions.',
    features: [
      'Closed-back design',
      'Wide frequency response',
      'High power handling',
      'Detachable cable',
      'Comfortable ear pads',
      'Foldable design',
    ],
    specifications: {
      'Driver Diameter': '50 mm',
      'Frequency Response': '5–40,000 Hz',
      Impedance: '24 ohms',
      Sensitivity: '106 dB',
      Weight: '275 g',
      Cable: 'Coiled & straight',
    },
    inStock: true,
    reviews: 118,
  },
];
